### ISSUE TITLE
Rename "Unofficial Talon Docs" page

### ISSUE THREAD

**Issue by 2shea** [TalonCommunity/Wiki#99]
The "Unofficial Talon Docs" page isn't very descriptive (isn't the whole wiki "unofficial talon docs"?). We could rename the page to be more about scripting and configuration, which is what it seems to be about.

**Comment by splondike** [comment]
I have a few thoughts about how the topic of scripting and configuration could be handled in the wiki which seem like they might fit OK into the scope of this issue. Interested to hear what folks think.

I'll start by saying what I think aegis' vision for Talon plugins is. My understanding of the idea is that programmers would be writing the .py files, and that the .talon files should be simple enough for non programmers to work with most of the time. In the longer term programmers would be defining multiple separate packages which each export a bunch of action, list, capture, tag, and scope definitions and implementations. The packages would also have suggested input bindings in the form of .talon files. End users would be able to easily override these input bindings as per their preference by editing the .talon files using a text editor (or maybe a GUI).

I wonder if the docs about configuration/scripting should have a similar split. We'd have a page for people who only want to do some basic .talon stuff, and a second one which goes into the level of detail of the current one.

The outline for the basic page might be:
```
Intro: If you want to add some new voice commands which use existing functionality (e.g. pressing keys or typing in text), this is the right page. Otherwise go to advanced.
Talon files: These can go anywhere in your user folder, the folder structure is just for your organisation. Simple explanation of matching and then how to press keys, insert text, sleep, and call existing actions. List some useful actions like copy/paste, mouse move etc.
Examples: List out some complete examples of matching programs by title and adding useful voice commands, defining settings.
```

The advanced page would look similar to what we've got now, I'd probably add a section describing aegis' philosophy of .talon vs .py, debugging commands (e.g. actions.list()), an examples section describing how to override actions in contexts etc. and maybe a pointer to some of the APIs available in Talon (e.g. canvas, TTS, mouse control etc.). I'd also keep the .talon section a bit separate so that the basic wiki users could come here to get a bit more power in their configuration without having to go full Python.

How does that sound? If y'all like it then we could start by renaming "Unofficial Talon Docs" to "Advanced Talon scripting". I would then be happy to take a first pass at the "Basic Talon scripting" page over the next couple of weeks.

**Comment by C-Loftus** [comment]
Closing since stale and will be fixed in refactor by splitting up the unofficial talon docs into separate sections for each distinct API category.
